_wandb:
    value:
        cli_version: 0.17.4
        python_version: 3.10.12
        t:
            1:
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            2:
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            3:
                - 13
                - 23
                - 55
            4: 3.10.12
            5: 0.17.4
            6: 4.42.3
            8:
                - 5
            12: 0.17.4
            13: linux-x86_64
