wandb_version: 1

batch_size:
  value: 64
dropout_rate:
  value: 0.3
epochs:
  value: 40
eps:
  value: 0.01
gnn_aggregation_type:
  value: sum
learning_rate:
  value: 0.0001
min_samples:
  value: 3
n_layers:
  value: 2
num_topics:
  value: 30
optim:
  value: adagrad
top_k:
  value: 2
